import type { LabChallenge } from '../types'

export const jsonChallenges: LabChallenge[] = [
  {
    id: 'jq-missing-owner',
    title: 'Resources without an owner tag',
    category: 'JSON (jq)',
    level: 'simple',
    type: 'command',
    scenario:
      'A cost review needs every resource to have an `owner` tag. **/root/resources.json** is an export of the subscription (an array of objects with name, type, resourceGroup, location and tags).',
    task: 'Print the **names** of the resources that have **no `owner` tag** (tag names are case-sensitive).',
    seedFiles: ['/root/resources.json'],
    hints: [
      '`.[]` iterates over the array.',
      'A missing key is `null` in jq: `select(.tags.owner == null)`.',
      "`jq -r '.[] | select(.tags.owner == null) | .name' /root/resources.json`",
    ],
    solutions: [
      `jq -r '.[] | select(.tags.owner == null) | .name' /root/resources.json`,
      `jq -r '.[] | select(.tags | has("owner") | not) | .name' /root/resources.json`,
    ],
    explanation: [
      { code: '.[]', note: 'One resource at a time.' },
      {
        code: 'select(.tags.owner == null)',
        note: 'Keep resources where the owner key is missing. "Owner" with a capital O does not count.',
      },
      { code: '.name', note: 'Print the name; -r prints it without quotes.' },
    ],
    checks: [{ kind: 'output', mode: 'unordered', label: 'Resources' }],
    hiddenVariant: 'A different subscription export.',
    followUp:
      'How would you get the same list straight from Azure with `az resource list --query`?',
    repoRef: null,
    tags: ['jq', 'tags'],
  },
  {
    id: 'jq-missing-tags',
    title: 'Which required tags are missing?',
    category: 'JSON (jq)',
    level: 'medium',
    type: 'command',
    scenario: 'Policy says every resource needs the tags **env**, **owner** and **costcenter**.',
    task: 'For each resource in **/root/resources.json** that is missing any of them, print `name: tag1,tag2` (the missing tags, in the order env, owner, costcenter). Skip resources that have all three.',
    seedFiles: ['/root/resources.json'],
    hints: [
      'jq can subtract arrays: `["a","b"] - ["b"]` is `["a"]`.',
      '`.tags | keys` gives the tag names a resource has.',
      '`jq -r \'.[] | (["env","owner","costcenter"] - (.tags | keys)) as $m | select($m | length > 0) | "\\(.name): \\($m | join(","))"\' /root/resources.json`',
    ],
    solutions: [
      `jq -r '.[] | (["env","owner","costcenter"] - (.tags | keys)) as $m | select($m | length > 0) | "\\(.name): \\($m | join(","))"' /root/resources.json`,
    ],
    explanation: [
      {
        code: '["env","owner","costcenter"] - (.tags | keys)',
        note: 'Required minus present = missing (array subtraction keeps the required order).',
      },
      { code: 'as $m', note: 'Save the result in a variable.' },
      { code: 'select($m | length > 0)', note: 'Only resources that miss something.' },
      { code: '"\\(.name): \\($m | join(","))"', note: 'String interpolation builds the line.' },
    ],
    checks: [{ kind: 'output', mode: 'unordered', label: 'Missing tags' }],
    hiddenVariant: 'A different subscription export.',
    followUp: 'How would you enforce this at deployment time instead of finding it afterwards?',
    repoRef: null,
    tags: ['jq', 'tags'],
  },
  {
    id: 'jq-count-types',
    title: 'Count resources by type',
    category: 'JSON (jq)',
    level: 'simple',
    type: 'command',
    scenario: 'You want a quick overview of what is in the subscription.',
    task: 'From **/root/resources.json**, print how many resources there are of each **type**, one per line as `<count> <type>`.',
    seedFiles: ['/root/resources.json'],
    hints: [
      '`group_by(.type)` makes an array of arrays, one per type.',
      'For each group, `length` is the count and `.[0].type` the type.',
      '`jq -r \'group_by(.type) | .[] | "\\(length) \\(.[0].type)"\' /root/resources.json`',
    ],
    solutions: [
      `jq -r 'group_by(.type) | .[] | "\\(length) \\(.[0].type)"' /root/resources.json`,
      "jq -r '.[].type' /root/resources.json | sort | uniq -c",
    ],
    explanation: [
      { code: 'group_by(.type)', note: 'Sort by type and group equal types together.' },
      { code: '.[] | "\\(length) \\(.[0].type)"', note: 'For each group, its size and its type.' },
      { code: "jq -r '.[].type' | sort | uniq -c", note: 'Or let the shell count.' },
    ],
    checks: [{ kind: 'output', mode: 'unordered', label: 'Counts per type' }],
    hiddenVariant: 'A different subscription export.',
    followUp: 'How would you output this as a JSON object like {"type": count}?',
    repoRef: null,
    tags: ['jq'],
  },
  {
    id: 'jq-prod-locations',
    title: 'Production resources and where they run',
    category: 'JSON (jq)',
    level: 'simple',
    type: 'command',
    scenario: 'A DR review needs a list of production resources and their regions.',
    task: 'From **/root/resources.json**, print `name,location` (no quotes) for every resource tagged **env=prod**.',
    seedFiles: ['/root/resources.json'],
    hints: [
      'Filter with `select(.tags.env == "prod")`.',
      'Build the line with string interpolation, or `[.name, .location] | join(",")`.',
      '`jq -r \'.[] | select(.tags.env == "prod") | "\\(.name),\\(.location)"\' /root/resources.json`',
    ],
    solutions: [
      `jq -r '.[] | select(.tags.env == "prod") | "\\(.name),\\(.location)"' /root/resources.json`,
      `jq -r '.[] | select(.tags.env == "prod") | [.name, .location] | join(",")' /root/resources.json`,
    ],
    explanation: [
      { code: 'select(.tags.env == "prod")', note: 'Only production resources.' },
      {
        code: '"\\(.name),\\(.location)"',
        note: 'Join two fields with a comma. (`@csv` would add quotes.)',
      },
    ],
    checks: [{ kind: 'output', mode: 'unordered', label: 'Production resources' }],
    hiddenVariant: 'A different subscription export.',
    followUp: 'When is @csv the better choice, and why?',
    repoRef: null,
    tags: ['jq'],
  },
  {
    id: 'jq-validate',
    title: 'Is the config valid JSON?',
    category: 'JSON (jq)',
    level: 'simple',
    type: 'command',
    scenario: 'A deploy failed with a parse error and you suspect a hand-edited config.',
    task: 'Print **VALID** if **/root/config.json** is valid JSON, otherwise **INVALID**.',
    seedFiles: ['/root/config.json'],
    hints: [
      'jq exits non-zero when it cannot parse its input.',
      '`jq empty` parses without printing anything.',
      '`jq empty /root/config.json 2>/dev/null && echo VALID || echo INVALID`',
    ],
    solutions: [
      'jq empty /root/config.json 2>/dev/null && echo VALID || echo INVALID',
      'if jq . /root/config.json >/dev/null 2>&1; then echo VALID; else echo INVALID; fi',
    ],
    explanation: [
      {
        code: 'jq empty file',
        note: 'Parse the file and output nothing; the exit status says whether it parsed.',
      },
      { code: '2>/dev/null', note: 'Hide the parse error message.' },
      { code: '&& echo VALID || echo INVALID', note: 'Choose the message from the exit status.' },
    ],
    checks: [{ kind: 'output', mode: 'exact', label: 'Result' }],
    hiddenVariant: 'The config has a trailing comma.',
    followUp: 'Why can `a && b || c` run c even when a succeeded? When is if/else safer?',
    repoRef: null,
    tags: ['jq', 'exit codes'],
  },
]
