import type { InterviewQuestion } from '../../../types'

/** FinOps, GitOps, AIOps and how the operations practices fit together. */
export const myOpsFinOpsGitOpsQuestions: InterviewQuestion[] = [
  {
    id: 'itv-myops-44',
    level: 'basic',
    kind: 'open',
    prompt: 'How do DevOps, GitOps, MLOps and AIOps differ?',
    probing: 'Whether you can explain what problem each practice solves and how they fit together.',
    answer: [
      'DevOps, GitOps, MLOps, and AIOps all rely on automation, feedback, measurement, version control, security, and continuous learning. Each one solves a different problem in the lifecycle.',
      '- **DevOps**: Primary focus: Software delivery and operations; Typical work: CI/CD, IaC, configuration, observability, collaboration, reliability\n- **GitOps**: Primary focus: Declarative infrastructure/application delivery; Typical work: Git as the source of truth, pull-based reconciliation (making the live system match Git), drift detection, policy, rollback\n- **MLOps**: Primary focus: Machine-learning lifecycle; Typical work: Data/versioning, training pipelines, registry, deployment, monitoring, drift and retraining\n- **AIOps**: Primary focus: Intelligent IT operations; Typical work: Event correlation, anomaly detection, root-cause help, forecasting, noise reduction, safe automated fixes',
      'DevOps builds reliable delivery. MLOps extends those same practices to data and models: it adds feature and data lineage, experiment tracking, a model registry, serving, drift and bias detection, and retraining.',
      'AIOps applies analytics and machine learning to operational monitoring data so teams can detect and prioritize issues faster. It has to explain its evidence clearly, ask a human before any risky action, take feedback, and limit what it can automate on its own. GitOps keeps the declared state versioned and continuously reconciled against the live system.',
      'A practical learning path: start with Linux, networking, Git, cloud, security, SQL/Python, CI/CD, containers, Kubernetes, and Terraform/Ansible, then add monitoring and logging. From there, add data pipelines and model lifecycle work for MLOps, and statistics, event correlation, and automation guardrails for AIOps.',
      'None of these practices replaces another. Together they cover building, delivering, operating, learning, and improving.',
    ],
    tags: ['devops', 'gitops', 'mlops', 'aiops'],
  },
  {
    id: 'itv-myops-45',
    level: 'advanced',
    kind: 'open',
    prompt: 'How do you optimize infrastructure cost without impacting performance or reliability?',
    probing:
      'Whether you separate waste from growth with unit costs and change things with performance and rollback criteria.',
    answer: [
      'I start by getting the evidence right: I break down cost by account, service, environment, owner, region, tag, SKU, and a real unit like cost per request or per customer. Then I compare that billing data against utilization, latency, errors, capacity forecasts, and SLOs.',
      "That comparison is what tells waste apart from legitimate growth, so I'm not just cutting an arbitrary percentage across the board.",
      'From there, typical actions include deleting confirmed orphaned non-production resources, scheduling resources to shut off when idle, right-sizing based on real usage percentiles and load tests, autoscaling with a safe minimum, storage lifecycle and tiering, controlling log retention and how many unique label combinations get tracked, more efficient data transfer, the right managed-service tier, and reserved or savings commitments for stable baseline load.',
      'Spot capacity only goes to workloads that can tolerate being interrupted.',
      "Often, improving the architecture or the application's own efficiency saves more than just shrinking instance sizes.",
      'Every change has clear performance and rollback criteria, and I canary it where I can. Budgets, anomaly alerts, ownership tags, cost estimates during IaC review, quotas, showback reporting, and regular reviews keep the optimization work going instead of it being a one-time push.',
      'After every change, I check that cost per unit actually improved and that SLOs are still being met.',
      '**AWS example (from a similar question)**',
      'Use tagging and Cost Explorer to find spending patterns, right-size EC2 from CloudWatch data plus autoscaling, use the Cluster Autoscaler and HPA on EKS, use spot instances for non-critical workloads, apply S3 lifecycle rules and DynamoDB autoscaling, and schedule off-hours scaling alongside Reserved Instances or Savings Plans.',
      '**Detailed interview approach:** I start with thorough tagging and AWS Cost Explorer to see spending patterns by team, application, and environment.',
      'For EC2, I look at CloudWatch metrics to find oversized instances and set up autoscaling with instance types that actually match the workload.',
      'For EKS clusters, I use the Kubernetes Cluster Autoscaler to adjust node counts based on pod demand, and the Horizontal Pod Autoscaler to scale deployments based on CPU and memory use. I use spot instances for non-critical workloads, spreading across instance types to avoid disruption.',
      'For storage, I use S3 lifecycle policies to move infrequently accessed data to cheaper tiers, and set up DynamoDB autoscaling to match actual throughput.',
      'Scheduled scaling through Terraform reduces resources during off-hours in non-production environments, and I regularly review Reserved Instance coverage and Savings Plans to keep discounts working for predictable workloads.',
      'This approach has cut costs by around 43% in practice while keeping the same performance targets.',
    ],
    followUps: [
      'How do you decide between Reserved Instances and Savings Plans?',
      'Which workloads are safe for spot capacity?',
    ],
    tags: ['finops', 'cost optimization'],
  },
  {
    id: 'itv-myops-46',
    level: 'advanced',
    kind: 'scenario',
    prompt: 'Your cloud bill increases by 40% overnight. How do you investigate it?',
    probing:
      'Whether you slice the bill against a baseline, check for compromise and contain only confirmed waste.',
    answer: [
      'I compare the affected day or hour against the normal baseline, broken down by service, account, region, SKU, usage type, tag, and resource ID.',
      'I check for recent deployments, autoscaling events, new resources, a pricing or commitment change, data egress, NAT traffic, log or metrics ingestion, snapshots, database I/O, serverless invocations, and marketplace charges.',
      'A sudden jump in compute or API usage is also a signal to check for leaked credentials or crypto-mining.',
      "I only shut down what I've confirmed is waste or a compromise: disable a leaked identity, cap runaway autoscaling or logging, stop non-production resources I own, or block a job that's clearly misbehaving. I never terminate an unfamiliar stateful production resource just because a cost dashboard flagged it.",
      'Cloud audit logs and the owner/tag metadata tell me who created or last changed the resource.',
      "Once it's fixed, I confirm application SLOs are healthy and billing has actually come back down. Then I add budget and anomaly alerts, require ownership tags, set quotas and scaling limits, tighten log retention policy, and add cost review to IaC changes.",
      'Finally, I write down whether the spike was waste, an attack, expected traffic growth, or just a tagging/allocation error.',
    ],
    followUps: [
      'How would you tell crypto-mining from real traffic growth?',
      'What guardrails would you add afterward?',
    ],
    tags: ['finops', 'cost', 'incident'],
  },
  {
    id: 'itv-myops-47',
    level: 'intermediate',
    kind: 'open',
    prompt: 'How do you scale observability storage and retention cost-effectively?',
    probing:
      'Whether you downsample metrics and tier log retention while keeping what alerts and compliance need.',
    answer: [
      'Aggregate and downsample older metrics (Prometheus remote write to Thanos/Cortex), use tiered log retention (hot/warm/cold), and set retention policies that match compliance requirements.',
      'Mini-case: we moved 30-day detailed metrics to Thanos with 90-day downsampled retention. That cut monitoring costs by 60% while keeping the accuracy we needed for alerts. **Detailed interview approach:** I compare cost by service, account, region, tag, SKU, and usage metric against the normal baseline and any recent deployments. I check whether the rise is from real traffic growth, runaway autoscaling, orphaned resources, log or egress volume, a pricing/commitment change, or compromised compute.',
      "I only contain what I've confirmed: budgets, scaling caps, quotas, or stopping non-production waste I own — I don't delete stateful production resources without being sure. Terraform plans get cost estimates, and changes above a threshold need policy approval.",
      'Required tags, anomaly alerts, right-sizing, schedules, lifecycle retention, reserved vs. spot choices, and owner-level cost visibility keep the optimization ongoing. I always check performance and SLOs after making a cost change.',
    ],
    tags: ['finops', 'observability', 'retention'],
  },
  {
    id: 'itv-myops-48',
    level: 'intermediate',
    kind: 'open',
    prompt: 'How do you set up cost-aware CI/CD pipelines to prevent runaway spend?',
    probing: 'Whether you estimate cost in the pipeline and require approval above a threshold.',
    answer: [
      'Add cost estimation to the pipeline so it estimates the infra cost of each change, set budget checks and alerts, use autoscaling and spot instances where they fit, and block a merge if the estimated cost goes over a threshold.',
      'Mini-case: a pipeline flagged that a proposed infra change would triple the monthly cost. That required manager approval before it could go through, which prevented an accidental large spend. **Detailed interview approach:** I compare cost by service, account, region, tag, SKU, and usage metric against the normal baseline and any recent deployments. I check whether the rise is from real traffic growth, runaway autoscaling, orphaned resources, log or egress volume, a pricing/commitment change, or compromised compute.',
      "I only contain what I've confirmed: budgets, scaling caps, quotas, or stopping non-production waste I own — I don't delete stateful production resources without being sure. Terraform plans get cost estimates, and changes above a threshold need policy approval.",
      'Required tags, anomaly alerts, right-sizing, schedules, lifecycle retention, reserved vs. spot choices, and owner-level cost visibility keep the optimization ongoing. I always check performance and SLOs after making a cost change.',
    ],
    tags: ['finops', 'ci/cd', 'cost estimation'],
  },
  {
    id: 'itv-myops-49',
    level: 'basic',
    kind: 'open',
    prompt: 'How do you integrate cost monitoring into DevOps pipelines?',
    probing: 'Whether you know how to pull billing data into the pipeline and alert on budget.',
    answer: [
      'Pull data from the GCP Billing API or Azure Cost Management, add cost checks into the pipeline, and alert when the estimated cost goes over budget.',
      '**Detailed interview approach:** I compare cost by service, account, region, tag, SKU, and usage metric against the normal baseline and any recent deployments. I check whether the rise is from real traffic growth, runaway autoscaling, orphaned resources, log or egress volume, a pricing/commitment change, or compromised compute.',
      "I only contain what I've confirmed: budgets, scaling caps, quotas, or stopping non-production waste I own — I don't delete stateful production resources without being sure. Terraform plans get cost estimates, and changes above a threshold need policy approval.",
      'Required tags, anomaly alerts, right-sizing, schedules, lifecycle retention, reserved vs. spot choices, and owner-level cost visibility keep the optimization ongoing. I always check performance and SLOs after making a cost change.',
    ],
    tags: ['finops', 'ci/cd', 'budgets'],
  },
  {
    id: 'itv-myops-50',
    level: 'intermediate',
    kind: 'open',
    prompt: 'How do you implement infrastructure cost optimization in Terraform?',
    probing:
      'Whether you can use Terraform variables, autoscaling, tags and lifecycle rules for cost control.',
    answer: [
      'Use variables for instance sizes, add auto-scaling groups, apply resource tags, and use lifecycle policies to clean up unused resources.',
      '**Detailed interview approach:** I compare cost by service, account, region, tag, SKU, and usage metric against the normal baseline and any recent deployments. I check whether the rise is from real traffic growth, runaway autoscaling, orphaned resources, log or egress volume, a pricing/commitment change, or compromised compute.',
      "I only contain what I've confirmed: budgets, scaling caps, quotas, or stopping non-production waste I own — I don't delete stateful production resources without being sure. Terraform plans get cost estimates, and changes above a threshold need policy approval.",
      'Required tags, anomaly alerts, right-sizing, schedules, lifecycle retention, reserved vs. spot choices, and owner-level cost visibility keep the optimization ongoing. I always check performance and SLOs after making a cost change.',
    ],
    tags: ['finops', 'terraform'],
  },
  {
    id: 'itv-myops-51',
    level: 'basic',
    kind: 'open',
    prompt:
      'What is the difference between push-based and pull-based deployment, and how do you choose?',
    probing:
      'Whether you understand who holds cluster credentials in each model and the trade-offs of each.',
    answer: [
      'In a push model, the CI/CD system logs into the target environment and sends the change directly — for example, by running `helm upgrade` or `kubectl apply` against a Kubernetes cluster.',
      '**Advantages** of the push model:',
      '- The pipeline can inject the exact image version it just built.\n- Helm deployments and one-off migration steps are straightforward.\n- Secrets can stay in the CI/CD secret store instead of Git.',
      '**Trade-offs** of the push model:',
      "- The CI/CD system needs network access and write permission to the cluster.\n- Cluster credentials and configuration become part of the delivery system's security boundary.\n- Deployment behavior is tied to how the pipeline is written.",
      "I secure this model with short-lived workload identity, a deployment `ServiceAccount` that has only the access it needs, protected environments, approval and policy gates, artifacts that don't change after they're built, and verification after every deployment.",
      '**Pull-based deployment**',
      "In a pull model, an in-cluster GitOps controller such as **Argo CD** or **Flux** reads the desired state from Git and continuously reconciles the cluster to match it — meaning it keeps correcting the live cluster until it looks like what's in Git.",
      'CI builds and publishes an artifact, then updates the desired version in the configuration repository. It never needs direct write access to the cluster.',
      '**Advantages** of the pull model:',
      "- Git gives you a reviewable desired state and a full deployment history.\n- The controller continuously detects and fixes drift on its own.\n- External CI systems don't need broad cluster credentials.\n- One GitOps platform can manage multiple clusters and tenants with clear repository and project boundaries.",
      '**Trade-offs** of the pull model:',
      "- Secret delivery needs extra design — something like External Secrets Operator, Vault, SOPS, or Sealed Secrets. Plaintext secrets must never be committed.\n- Controller, repository, and multi-tenant permissions need careful isolation.\n- A bad commit to the desired state keeps getting reapplied until it's reverted or sync is paused.",
      '**Choosing between them**',
      'I choose based on security boundaries, auditability, network reachability, rollback needs, who owns operations, and what the workload actually needs. A common production setup uses CI for build, test, scanning, signing, and publishing the artifact, then GitOps for deployment and correcting drift.',
      'Rollback in GitOps is usually a reviewed Git revert to the last known-good image or configuration, followed by reconciliation and a health check. Any emergency manual change has to be captured back into Git, or the controller will correctly treat it as drift and undo it.',
    ],
    tags: ['gitops', 'deployment', 'argo cd'],
  },
  {
    id: 'itv-myops-52',
    level: 'intermediate',
    kind: 'open',
    prompt: 'Explain the Argo CD architecture and its end-to-end workflow.',
    probing:
      'Whether you know the Argo CD components, sync and health states, and the risks of pruning.',
    answer: [
      '**Argo CD** is a pull-based GitOps continuous-delivery controller for Kubernetes.',
      "It's made up of a few pieces: the API server handles the UI, CLI, authentication, and RBAC; the repository server fetches Git/Helm/Kustomize content and renders the manifests; the application controller compares the desired state with the live state and reconciles any difference; Redis caches state; Dex or an external OIDC provider can add SSO; and `ApplicationSet` generates multiple Applications at once.",
      "An application's sync state is either **Synced** or **OutOfSync**, and its health state is one of **Healthy**, **Progressing**, **Degraded**, **Missing**, **Unknown**, or **Suspended**. Automatic sync can also enable self-heal and pruning, but pruning needs protection — deleting an object from Git will delete it from the cluster too.",
      "Argo CD renders Helm templates itself; it doesn't run releases by calling `helm install` inside the cluster.",
      'The end-to-end flow looks like this: a developer makes a change, CI tests, scans, builds, and signs an image, the registry stores that image (the digest never changes after this point), the reviewed GitOps repository gets its manifests or chart values updated, Argo CD detects the commit, compares it to the live state and syncs, Kubernetes reconciles the difference, and then health and SLOs get verified.',
      'Rollback is either a Git revert or a controlled Argo CD rollback, followed by verification.',
      "Public repositories don't need credentials, but you still want to verify where the content came from. Private repositories should use a scoped deploy key, a GitHub App, or a token stored in Argo CD's protected secret mechanism.",
    ],
    tags: ['argo cd', 'gitops'],
  },
  {
    id: 'itv-myops-53',
    level: 'advanced',
    kind: 'open',
    prompt: 'How do you implement GitOps for both apps and infra while preventing config drift?',
    probing:
      'Whether you make Git the source of truth, capture emergency changes back into Git and guard pruning.',
    answer: [
      'Keep declarative manifests and Helm charts in Git, use Argo CD or Flux to auto-sync clusters, set up automated drift detection with auto-revert, and require pull requests plus branch protection for any change.',
      'Mini-case: after a manual hotfix caused drift in production, Argo CD detected it and auto-reverted to the Git state. We then applied the same fix properly through a pull request, so it stayed auditable. **Detailed interview approach:** Git holds the reviewed desired configuration, and every version in it stays unchanged once committed. Argo CD or Flux continuously compares that with the live cluster and reconciles any difference — meaning it makes the actual state match Git.',
      'I keep environment permissions and repositories separate, require branch protection and policy/security checks, and give the controller only the cluster scope it actually needs.',
      'A manual emergency change might pause sync temporarily, but it has to be captured back into a pull request right away. Otherwise, the next reconciliation will correctly undo it, since Git is the source of truth. Rollback just means reverting Git to the last known-good commit, then syncing and checking health and SLOs.',
      "Secrets go through an external-secrets or encrypted-secret workflow — never as plaintext in Git. I monitor sync failures, drift, controller access, and audit events, and destructive pruning has explicit safeguards so a deletion in Git can't silently wipe out something important.",
      '**From a similar question (GitOps in DevOps workflows)**',
      'Use Argo CD or Flux, keep infra and app configs in Git, sync automatically with Kubernetes, and roll back by reverting the Git commit.',
      '**Detailed interview approach:** Git holds the reviewed desired configuration, and every version in it stays unchanged once committed. Argo CD or Flux continuously compares that with the live cluster and reconciles any difference — meaning it makes the actual state match Git.',
    ],
    followUps: [
      'What happens to a manual hotfix when self-heal is on?',
      'How do you deliver secrets in a GitOps model?',
    ],
    tags: ['gitops', 'drift', 'argo cd', 'flux'],
  },
  {
    id: 'itv-myops-54',
    level: 'intermediate',
    kind: 'open',
    prompt: 'How do you implement GitOps rollback?',
    probing:
      'Whether you know rollback is a Git revert in GitOps and can also roll back a Deployment safely.',
    answer: [
      "Revert the commit in Git, and Argo CD or Flux automatically syncs the cluster back — that's the whole rollback.",
      '**Detailed interview approach:** I use a deployment strategy with realistic readiness and startup probes, graceful shutdown, and enough spare capacity. I pick `maxUnavailable` and `maxSurge` based on the replica count and availability target — setting zero unavailable only makes sense if the cluster can actually host the extra surge capacity.',
      "I deploy a specific image digest that won't change underneath me, watch `kubectl rollout status`, pod events, error rate, latency, and business checks, and pause if the new ReplicaSet looks unhealthy. To roll back, I use `kubectl rollout undo deployment/<name>`, or in GitOps, a Git revert — then I verify it worked.",
      'PodDisruptionBudgets, spreading across multiple zones, backward-compatible config and database changes, and a tested rollback path are what make the update genuinely low-risk.',
    ],
    tags: ['gitops', 'rollback', 'kubernetes'],
  },
  {
    id: 'itv-myops-55',
    level: 'basic',
    kind: 'open',
    prompt: 'What is AIOps, and how is it related to observability?',
    probing:
      'Whether you know AIOps depends on good observability data and still needs human verification.',
    answer: [
      'AIOps means using analytics and machine learning to improve IT operations. Observability is what collects and connects the raw evidence — metrics, logs, traces, topology, and changes. AIOps takes that evidence and uses it for anomaly detection, grouping related events, ranking impact, helping find the probable cause, forecasting, and safely automating a fix.',
      'For example, instead of paging separately for pod CPU throttling, API latency, and HPA saturation, AIOps can group all three into one incident, line up the start time with a recent deployment, and recommend restoring the known-good CPU requests. The team still checks that evidence before acting on it.',
      'Without good monitoring data, clear ownership, and real runbooks, AIOps just ends up automating noisy guesses.',
    ],
    tags: ['aiops', 'observability'],
  },
  {
    id: 'itv-myops-56',
    level: 'advanced',
    kind: 'open',
    prompt: 'Describe an end-to-end AIOps incident flow.',
    probing:
      'Whether you can describe correlation, ranking, runbook actions and verification, and roll it out carefully.',
    answer: [
      'Collectors bring in normalized monitoring data and change events, tagged with service, environment, region, and ownership. Correlation groups the symptoms together by time, topology, and dependency.',
      "Anomaly and SLO logic detects real impact, and the system ranks the likely causes, backed by traces, logs, metrics, and recent changes. It recommends a runbook — a low-risk, pre-approved action might run automatically, while anything riskier needs a human's approval.",
      'The platform then checks the real user transaction and SLO, rolls back if it needs to, records every decision, and learns from the confirmed outcome.',
      'When rolling this out, I start with one high-volume, well-understood type of incident and evaluate it against historical data, comparing it to existing rules and what a human would have decided, before I let it run automation on its own.',
      '**Key points from my AIOps summary**',
      '**AIOps** applies analytics and machine learning to IT operations data. It helps teams spot unusual behavior, group related events together, prioritize what matters most, assist with diagnosis, forecast capacity, and safely automate repeatable responses.',
      "**Observability** supplies the raw evidence: metrics, logs, traces, service relationships, deployment or configuration events, and who owns each service. AIOps uses those signals — it doesn't replace them.",
      "It also doesn't replace instrumentation, SRE ownership, or having someone lead an incident.",
      'A useful result looks like real evidence: "latency began after version 42, it affects two regions, traces point to database pool exhaustion, and a rollback fixed this same pattern before." A vague anomaly score on its own isn\'t useful.',
      '**What automation needs:**',
      "- Confidence thresholds\n- An identity with only the access it needs\n- Preconditions before it acts\n- Rate limits and a capped blast radius\n- A dry-run mode\n- Approval for anything risky\n- A rollback path and a kill switch\n- Audit evidence that can't be changed after the fact\n- A check against the SLO after the action runs",
      '**What to measure:** detection precision and recall, how much duplicate noise gets reduced, whether alerts are actually actionable, time to detect/acknowledge/restore, whether the top-ranked root cause is usually right, how often the fix actually works, and how often an action turns out to be unsafe.',
      'Feedback has to tell a temporary workaround apart from a real fix — otherwise the system just learns to keep restarting a service instead of ever fixing the underlying leak.',
    ],
    code: [
      {
        title: 'AIOps flow',
        language: 'text',
        code: `monitoring data and changes -> clean and add context -> group related events and detect unusual behavior
-> rank impact/probable causes -> recommend action
-> approval or bounded runbook -> verify -> learn`,
      },
    ],
    followUps: [
      'How would you evaluate the AIOps tool against past incidents?',
      'Which actions would you never automate?',
    ],
    tags: ['aiops', 'incident', 'automation'],
  },
  {
    id: 'itv-myops-57',
    level: 'advanced',
    kind: 'open',
    prompt: 'Walk through an AIOps incident flow for Kubernetes CPU throttling.',
    probing:
      'Whether you can connect Prometheus data, context, a bounded runbook and verification in one concrete flow.',
    answer: [
      'AIOps means applying analytics and machine learning to IT operations. Its job is to improve monitoring and response, not to replace the whole software-delivery lifecycle. A practical CPU-throttling flow looks like this:',
      '1. **Prometheus** collects container CPU usage and throttling counters.\n2. **Alerting** detects sustained throttling and attaches context: the service, cluster, deployment, and any recent changes.\n3. The **AIOps layer** checks the signal against recent deployments, config changes, traffic increases, node pressure, and similar past incidents.\n4. It **recommends a limited action**, such as restoring known-good resource requests, scaling replicas, or rolling back a bad release.\n5. An **approved runbook** applies the change, watches the rollout, and confirms that throttling, latency, and errors return to normal.\n6. The platform **notifies the team** and stores the evidence, decision, action, and result for audit and future learning.',
      'Automatic fixes need confidence thresholds, an identity with only the access it needs, limits on how big a change can be, human approval for risky actions, a rollback path, and a check afterward. Increasing CPU blindly can hide inefficient code or just push the pressure onto another dependency.',
      'Tools like PagerDuty, Datadog, Dynatrace, ManageEngine, Prometheus, Grafana, and various automation platforms can all play a part, but AIOps is an approach to running operations, not one single product.',
    ],
    followUps: [
      'Why can blindly increasing CPU limits make things worse?',
      'What approval would you require before the runbook acts?',
    ],
    tags: ['aiops', 'kubernetes', 'cpu throttling'],
  },
  {
    id: 'itv-myops-58',
    level: 'advanced',
    kind: 'open',
    prompt: 'How do you make an AIOps fix safe?',
    probing:
      'Whether you require preconditions, limits, a kill switch and verification before automation acts.',
    answer: [
      "I require a specific, confidently detected condition, a fresh check of the current state, an identity with only the access it needs, resource and rate limits, a cap on attempts, a timeout, dry-run evidence, a kill switch, rollback, and audit logs that can't be altered after the fact.",
      'Anything involving stateful deletion, broad access changes, data recovery, or a security incident stays under human control.',
      "After every action, I run the original synthetic or business transaction and check errors, latency, saturation, and dependencies. If that check fails, the automation stops and escalates — it doesn't just keep looping.",
      'I track false correlations and any action that turned out unsafe or ineffective, and I expire old approvals whenever the architecture changes.',
    ],
    followUps: [
      'What should happen when the verification check fails?',
      'When do old approvals expire?',
    ],
    tags: ['aiops', 'automation', 'safety'],
  },
  {
    id: 'itv-myops-59',
    level: 'intermediate',
    kind: 'scenario',
    prompt: 'An AIOps tool reports an anomaly but users see no problem. What do you do?',
    probing: 'Whether you check the anomaly against user-facing SLIs and handle it without paging.',
    answer: [
      "I don't act on the anomaly score alone. I look at the underlying feature and its baseline, seasonality, any deployment or traffic changes, missing data, changes to labels or topology, and whether the real user-facing SLIs are still healthy.",
      'It might be an early capacity warning, a legitimate new pattern, or the model itself drifting.',
      'I keep the event as non-paging evidence, only tune the segmentation or time window after actually analyzing it, and measure the impact of false positives. If it does point to a real future risk, I open a capacity ticket or a lower-severity forecast alert instead of paging anyone.',
      'I judge the model against confirmed incidents — not by how many anomalies it happens to flag.',
    ],
    tags: ['aiops', 'anomaly detection'],
  },
  {
    id: 'itv-myops-60',
    level: 'intermediate',
    kind: 'open',
    prompt: 'What is AgentOps, and what does running AI agents in production need?',
    probing:
      'Whether you see AI agents as production workloads that need versioning, tracing, limits and approval paths.',
    answer: [
      'Running AI agents in production takes more than just calling an LLM. **AgentOps** covers multi-step and tool-calling workflows, scheduling, retries, state and memory, observability, evaluation, cost, security, and human approval.',
      'An orchestration platform can run branches and retries on Kubernetes and keep track of workflow state, but production also needs prompt and tool versioning, trace correlation, redaction of sensitive data, permission boundaries, quality evaluation, timeout and budget limits, a safe fallback, and an auditable approval path.',
      'Python, Kubernetes, and an orchestrator such as Flyte make a solid open-source learning stack. The architecture matters more than any one tool.',
    ],
    tags: ['agentops', 'ai', 'operations'],
  },
  {
    id: 'itv-myops-61',
    level: 'advanced',
    kind: 'open',
    prompt: 'How do you manage a large fleet of Kubernetes clusters?',
    probing:
      'Whether you treat clusters as a managed fleet with standard provisioning, GitOps, secrets and a small blast radius per change.',
    answer: [
      "Once you're running tens or hundreds of clusters, treat them as a managed fleet rather than one-off installs:",
      '- **Cluster API** or a cloud fleet service standardizes how clusters get created, upgraded, and retired across accounts, subscriptions, regions, and environments.\n- **Terraform** manages cloud and cluster infrastructure through reviewed modules, with separate state per team and blast radius.\n- **Argo CD** or **Flux** deploys versioned desired state. **Helm** or **Kustomize** provides reusable application packaging.\n- **Vault** or an external-secrets system injects secrets so plaintext values never get committed.\n- A **service mesh** is worth adopting only when its mTLS, policy, and traffic-control benefits outweigh the extra operational cost.\n- **Central metrics, logs, traces, dashboards, and alert routing** give fleet-wide visibility while still keeping each cluster isolated.',
      'Fleet operations also need a version-skew policy, upgrade rings, admission policy, tenant isolation, capacity and cost reporting, tested backup and restore, and a break-glass process. The goal is repeatable control with a small blast radius per change, not one highly privileged system that can touch every cluster with no safeguards.',
    ],
    followUps: [
      'How do upgrade rings reduce risk?',
      'How do you keep one fleet tool from becoming a single all-powerful system?',
    ],
    tags: ['kubernetes', 'fleet', 'cluster api', 'gitops'],
  },
]
