import type { InterviewQuestion } from '../../../types'

/** Monitoring AWS, Azure, Kubernetes, hosts, databases, pipelines, IaC and monitoring cost. */
export const myMonitoringPlatformQuestions: InterviewQuestion[] = [
  {
    id: 'itv-mymon-43',
    level: 'basic',
    kind: 'open',
    prompt: 'What is the difference between CloudWatch and CloudTrail?',
    probing:
      'Whether you know CloudWatch is operational monitoring and CloudTrail is the API audit trail.',
    answer: [
      'CloudWatch holds operational monitoring data: metrics, logs, dashboards, alarms, synthetic checks, and event integrations. CloudTrail records AWS API activity for audit and investigation.',
      'In practice, I use CloudWatch to spot that latency or errors went up, then use CloudTrail to check whether a deployment role or an administrator changed the load balancer, a security policy, or a scaling setting around that same time.',
      "CloudTrail isn't a substitute for application tracing, and CloudWatch alone doesn't give a full identity audit trail. In production, I use centralized, protected CloudTrail trails, turn on the data events that matter, enable encryption and retention, make sure CloudWatch alarms are actually actionable, and test that SNS or the incident tool really receives them.",
      '**CloudWatch**: CloudWatch collects AWS service and custom metrics, logs, Logs Insights queries, alarms, dashboards, synthetic checks, and event-driven integrations.',
      'Common signals to watch:',
      '- **EC2**: How close resources are to their limits, instance status checks\n- **Lambda**: Errors, duration, throttles\n- **ALB**: Latency, HTTP error rates\n- **ECS / EKS**: Service health\n- **RDS**: Capacity, connection count\n- **SQS**: Queue depth, message age',
      "Route actionable alarms through SNS or an incident-management platform, and actually test the full notification path — don't assume it works just because the alarm exists.",
      '**CloudTrail**: CloudTrail is an audit trail for AWS API activity. Each record shows the principal, the action, the time, the source, the target, and the result.',
      'Best practice: centralize organization trails in a protected account, turn on the management and data events you actually need, encrypt and retain the logs, and alert on high-risk changes — things like policy changes, identity changes, logging being disabled, key changes, or a resource becoming publicly accessible.',
      '**Using them together**',
      "Compare a CloudWatch symptom, like a latency spike or an error rate increase, against deployment and configuration events, then confirm the cause with CloudTrail evidence of what actually changed. CloudTrail tells you what changed and who changed it; it isn't an application-performance monitor on its own.",
    ],
    tags: ['aws', 'cloudwatch', 'cloudtrail'],
  },
  {
    id: 'itv-mymon-44',
    level: 'intermediate',
    kind: 'scenario',
    prompt: 'Logs are not uploading from a healthy EC2 instance to S3. How do you investigate?',
    probing:
      'Whether you check the collector, the effective identity, explicit denies and KMS permissions before changing anything.',
    answer: [
      'First I confirm the log collector is actually reading current files, that its local spool disk is healthy, and that it attempted an upload at all.',
      'Then I check permissions. I run `aws sts get-caller-identity` to see which role the instance is actually using, and check the target bucket, region, and prefix. I look for `s3:PutObject` permission, any explicit denies coming from the bucket policy, an SCP, or a permissions boundary, and the KMS `Encrypt`/`GenerateDataKey` permissions if the bucket uses KMS encryption. I also check required tags or conditions, clock skew, and multipart upload failures.',
      "I look at the collector's own error logs and at CloudTrail data events for that bucket, without ever printing credentials to the screen.",
      'Once I find the real cause, I fix that one thing: the collector, the IAM policy, the KMS permission, the path, or the storage config. Then I verify a fresh object lands with the right encryption and metadata, and that downstream consumers pick it up.',
      "To stop it recurring, I use instance or task roles instead of long-lived keys, keep permissions scoped to only what's needed, and alert on collector backlog, upload age, and error counts.",
      '**Diagnosing missing S3 log uploads**',
      '1. Check the collector: is it reading the log path, and is there a backlog?\n2. Check disk and spool health on the source host.\n3. Confirm which AWS identity the collector is actually using.\n4. Check `s3:PutObject` permission, and look for denies from the bucket policy, an SCP, or a permissions boundary.\n5. If the bucket uses KMS, check the required encryption permissions.\n6. Check region, prefix, and multipart upload errors.',
      "CloudTrail data events and the collector's own metrics tell you whether AWS rejected the request or the collector never attempted one in the first place.",
      "Once fixed, verify a fresh object lands with the correct encryption, and set up alerts on upload age and failure count so it doesn't go unnoticed again.",
    ],
    tags: ['aws', 's3', 'iam', 'logging'],
  },
  {
    id: 'itv-mymon-45',
    level: 'intermediate',
    kind: 'scenario',
    prompt: 'How would you monitor an EC2 CPU incident?',
    probing:
      'Whether you check duration, impact, credits and the CPU breakdown and capture evidence before rebooting.',
    answer: [
      "First I check the basics in CloudWatch: how long the high CPU has lasted, whether customers are actually affected, instance status checks, autoscaling activity, any recent deployments or config changes, and CPU credit exhaustion if it's a burstable instance type.",
      'Then on the host itself, I compare load average, user versus system CPU time, CPU steal, I/O wait, and the top processes.',
      "To stabilize things, I shift traffic away, scale out, roll back a bad deployment, or stop a runaway job once I've confirmed it's safe to stop. I avoid rebooting before I've captured evidence of what was happening.",
      'The real fix depends on what I find. It could be profiling the code, fixing a slow query or cache, correcting a scheduled job, improving autoscaling triggers, or moving to a better-suited instance type.',
      'Afterward, I confirm user-facing latency and error rates are back to normal under load, and I set up alerts for CPU running close to its limit, credit exhaustion, request queueing, and failed scaling events.',
    ],
    tags: ['aws', 'ec2', 'cpu', 'cloudwatch'],
  },
  {
    id: 'itv-mymon-46',
    level: 'basic',
    kind: 'open',
    prompt: 'What are the core building blocks of Azure Monitor?',
    probing:
      'Whether you know diagnostic settings, Log Analytics, Application Insights, alerts and workbooks and how they connect.',
    answer: [
      'Azure Monitor is the umbrella platform for Azure metrics, logs, traces, alerts, workbooks, and integrations. Platform metrics give you numeric time series for each resource.',
      '**Core building blocks**',
      "- **Diagnostic settings**: Route a resource's logs and metrics to Log Analytics, Storage, Event Hubs, or a partner tool\n- **Log Analytics**: Stores and queries log data using KQL (Kusto Query Language)\n- **Application Insights**: Captures application requests, dependencies, exceptions, traces, and availability tests, usually through OpenTelemetry\n- **Alerts and action groups**: Fire notifications or trigger automation when a condition is met\n- **Workbooks**: Build reusable dashboards and reports on top of the data above",
      'Workspace boundaries should reflect who needs access, data residency rules, retention requirements, ownership, and cost.',
    ],
    tags: ['azure', 'azure monitor'],
  },
  {
    id: 'itv-mymon-47',
    level: 'intermediate',
    kind: 'open',
    prompt: 'How do you monitor Azure resources in production?',
    probing:
      'Whether you monitor from the user journey and use the Activity Log and dependencies during incidents.',
    answer: [
      "I start with the user journey and the service's goals. Then I use Azure Monitor metrics, resource diagnostic settings, Log Analytics, Application Insights, the Activity Log, alerts with action groups, and workbooks.",
      'I watch availability, latency, errors, traffic, saturation (how close a resource is to its limit), dependency failures, queue age, and capacity — not just VM CPU.',
      'For an incident, I fix the time window and scope first. Then I compare healthy and unhealthy traffic, check deployment and Activity Log changes, follow Application Insights dependencies, and query the relevant resource logs. I fix the confirmed cause and confirm recovery using the original transaction.',
      'Monitoring is deployed through IaC or Policy. Access and retention are controlled, and alert delivery is tested regularly.',
      '**Investigating an incident**',
      'Start with the affected transaction. Compare Application Insights requests and dependencies against resource metrics, Log Analytics data, deployment markers, and Azure Activity Log changes. Confirm recovery by running the same transaction again.',
    ],
    tags: ['azure', 'azure monitor', 'monitoring'],
  },
  {
    id: 'itv-mymon-48',
    level: 'basic',
    kind: 'open',
    prompt: 'What are Log Analytics and KQL?',
    probing: 'Whether you can write a scoped KQL query and know workspace design concerns.',
    answer: [
      'Log Analytics is the Azure Monitor tool for querying workspace log tables. KQL, or Kusto Query Language, is a read-only pipeline language you use to filter data, select columns, parse fields, summarize results, and join tables.',
      'I scope the time range and resource early. I confirm the right table and schema with a known event, and I avoid expensive broad joins. Once a query is proven, I turn it into a saved function, a workbook, or an alert. Workspace design also covers region, RBAC, retention, data residency, and ingestion cost.',
    ],
    code: [
      {
        title: 'KQL: requests, failures and P95 by 5 minutes',
        language: 'text',
        code: `AppRequests
| where TimeGenerated > ago(30m)
| summarize Requests=count(),
            Failures=countif(Success == false),
            P95=percentile(DurationMs, 95)
  by bin(TimeGenerated, 5m)`,
      },
    ],
    tags: ['azure', 'log analytics', 'kql'],
  },
  {
    id: 'itv-mymon-49',
    level: 'intermediate',
    kind: 'scenario',
    prompt: 'What is Application Insights, and how would you investigate a slow API?',
    probing:
      'Whether you use percentiles, deployment markers and dependency timing to find the slow part of an API.',
    answer: [
      'Application Insights captures requests, dependencies, exceptions, traces, availability tests, and distributed correlation through SDK or OpenTelemetry instrumentation.',
      'To investigate a slow API, I compare P50/P95/P99 latency, failure rate, and deployment markers. I pick out slow traces and separate application processing time from SQL, cache, or external dependency time.',
      'I verify the suspected dependency using its own metrics and logs before I change capacity or code.',
      'I also set up sampling, filter out sensitive data, configure trace propagation and retention, and run meaningful synthetic tests. After a rollback, a query fix, or another change, I repeat the same transaction and confirm that latency, errors, and dependency health have recovered.',
    ],
    tags: ['azure', 'application insights', 'apm'],
  },
  {
    id: 'itv-mymon-50',
    level: 'intermediate',
    kind: 'open',
    prompt: 'How do you create and validate an Azure Monitor alert?',
    probing:
      'Whether your alerts are actionable, deployed as code and tested for both firing and resolving.',
    answer: [
      'I pick a resource and an actionable metric or log signal. Then I set a threshold or dynamic condition, an evaluation frequency and window, a severity, and an action group. Log alerts use a KQL query, tested against historical and known data.',
      'The notification should include the environment, resource, observed value, owner, dashboard, and runbook.',
      'I deploy the alert through Bicep, Terraform, or Policy. I trigger a safe test condition to confirm the notification fires and creates an incident, then confirm it resolves correctly. Alert processing rules handle planned maintenance windows.',
      'I track noise and missed incidents, and tune the rule over time rather than leaving an untested portal configuration in place.',
      '**What a good alert looks like**',
      'A production alert needs:',
      '- A signal that matters to users\n- A threshold or dynamic condition\n- An evaluation window\n- A severity level\n- An owner\n- An action group\n- A linked runbook',
      'Test both the firing notification and the resolved notification before you trust the alert.',
    ],
    tags: ['azure', 'alerts', 'action groups'],
  },
  {
    id: 'itv-mymon-51',
    level: 'basic',
    kind: 'open',
    prompt: 'What are Azure diagnostic settings?',
    probing:
      'Whether you know diagnostic settings route per-resource categories and must be verified with a known event.',
    answer: [
      "Diagnostic settings route a resource's supported log and metric categories to Log Analytics, Storage, Event Hubs, or a partner tool. Categories differ by resource type, so nothing is enabled everywhere by default.",
      'I choose destinations based on query needs, SIEM requirements, archiving, retention, and cost. I deploy settings consistently, trigger a known event, and check that the resource ID, timestamp, and fields show up correctly at the destination. I also alert on ingestion gaps and lock down the destination against unauthorized deletion.',
      '**Deploying monitoring correctly**',
      'Data Collection Rules and diagnostic settings need to be deployed consistently, through IaC or Policy rather than by hand. After deployment, generate a known event and confirm it actually arrives. An enabled setting with no confirmed data flowing through it is not real monitoring.',
    ],
    tags: ['azure', 'diagnostic settings'],
  },
  {
    id: 'itv-mymon-52',
    level: 'intermediate',
    kind: 'open',
    prompt: 'What metrics prove Kubernetes cluster health?',
    probing:
      'Whether you monitor control plane, nodes, workloads and applications, and alert on user symptoms.',
    answer: [
      'I look at four layers.',
      'At the control plane: API server availability, latency, and error rate; scheduler and controller queue depth; and etcd health, where I own it.',
      'At the node level: whether nodes are Ready, CPU and memory use, disk space, inodes and process limits, network health, and the state of kubelet, the container runtime, CNI, and CoreDNS.',
      'At the workload level: Pending Pods, restart counts, unavailable replicas, Job status, HPA and PDB behavior, PVC/CSI health, and Ingress and certificate status.',
      "Most importantly, I watch the application itself: availability, latency, traffic, errors, saturation, and at least one real business transaction. Saturation means how close a resource is to its limit. Healthy nodes don't prove healthy users, so this layer matters more than the others.",
      'Alerts focus on symptoms that actually need action — an SLO burning too fast, zero Ready replicas, a node under pressure. Diagnostic detail belongs in dashboards, not alerts. I validate every alert, tag it with cluster, version, and deployment labels, and keep an eye on cardinality — too many unique label combinations driving up cost and noise.',
      '**The four layers**: Kubernetes monitoring breaks down into four layers, from the platform down to the actual user experience:',
      '- **Control plane**: API availability, latency, and errors; scheduler and controller queue depth; `etcd` health (self-managed clusters only)\n- **Nodes**: `Ready` condition, CPU/memory, disk/inodes/PIDs, network, `kubelet`, runtime, CNI, CoreDNS, certificate expiry\n- **Workloads**: Pending Pods, restarts, unavailable replicas, Jobs, HPA, PDB, PVC/CSI, Ingress health\n- **Applications**: Availability, latency, traffic, errors, saturation, dependencies, business transactions',
      "Saturation means how close a resource is to its limit — it's the layer most likely to catch a problem users actually feel.",
    ],
    tags: ['kubernetes', 'monitoring', 'cluster health'],
  },
  {
    id: 'itv-mymon-53',
    level: 'basic',
    kind: 'open',
    prompt: 'What does the standard Kubernetes monitoring stack look like?',
    probing:
      'Whether you know kube-prometheus-stack, log shipping and tracing, and that probes are not monitoring.',
    answer: [
      '`kube-prometheus-stack` commonly provides the Prometheus Operator, Grafana, Alertmanager, `node-exporter`, and `kube-state-metrics`. On top of that, add application `ServiceMonitor`s, centralized structured logs shipped through Fluent Bit to Loki, Elasticsearch, or cloud logging, and OpenTelemetry traces sent to Tempo, Jaeger, or a vendor platform.',
      'Liveness and readiness probes change how a workload behaves — they restart or reroute traffic away from unhealthy Pods — but they are not a monitoring system on their own.',
    ],
    tags: ['kubernetes', 'kube-prometheus-stack'],
  },
  {
    id: 'itv-mymon-54',
    level: 'advanced',
    kind: 'open',
    prompt: 'How do you implement centralized monitoring for many Kubernetes or AKS clusters?',
    probing:
      'Whether you can centralize multi-cluster monitoring without breaking tenant isolation or creating one failure domain.',
    answer: [
      'Each cluster runs its own collectors and exporters, tagged with a stable identity: cluster name, subscription or account, region, and environment.',
      'Metrics are remote-written to a managed Prometheus setup, or to a Thanos/Mimir architecture, and Grafana provides shared dashboards with access scoped per tenant.',
      'Logs flow through buffered node agents into a central backend — Log Analytics, Loki, OpenSearch, or whatever platform is standard — while OpenTelemetry handles trace export. On Azure this often combines Azure Monitor/Container Insights, Managed Prometheus, and Managed Grafana.',
      "I design for high availability, retention, cost, network and private access, and tenant isolation. I watch for dropped data and backpressure, and I test what happens when a cluster, backend, or network link fails. Central visibility isn't an excuse to give every team access to every cluster, and it shouldn't turn into one shared failure domain that takes every cluster down at once.",
      '**Multi-cluster monitoring**',
      "Attach stable cluster, account, region, and environment labels to everything. Keep tenant access boundaries in place so one team's dashboard access doesn't leak into another's cluster. Use remote write, or Thanos/Mimir/managed Prometheus, to run queries across clusters, and centralize dashboards without turning any single cluster into a point of failure for the rest.",
      "**Testing and cost**: Test the failure scenarios directly: a missing scrape, a dropped log, broken alert routing, a backend outage. And monitor the monitoring stack itself — its ingestion rate, storage use, cardinality (the number of unique label combinations it's tracking), and cost.",
      '**Monitoring multiple AKS clusters**',
      'For several AKS clusters, use:',
      "- Azure Monitor container insights data where it's needed\n- Azure Managed Prometheus, or self-managed Prometheus, for Kubernetes metrics\n- Azure Managed Grafana, or Grafana, for shared views across clusters\n- Centralized but access-controlled Log Analytics workspaces",
      'Add cluster, subscription, region, and environment labels, but avoid high-cardinality dimensions — labels with too many unique values, such as raw user or request IDs, which drive up cost and slow down queries.',
    ],
    followUps: [
      'How would you label metrics so you can query across clusters?',
      'How do you stop the central backend becoming a single point of failure?',
    ],
    tags: ['kubernetes', 'aks', 'multi-cluster', 'prometheus'],
  },
  {
    id: 'itv-mymon-55',
    level: 'intermediate',
    kind: 'open',
    prompt: 'How do you monitor Kubernetes logs?',
    probing:
      'Whether you know `kubectl logs` is for debugging and production needs a collector, a backend and structured logs.',
    answer: [
      "`kubectl logs` and `kubectl logs --previous` are fine for debugging one Pod right now. They aren't a production logging strategy.",
      'In production, applications write structured logs to stdout/stderr. A DaemonSet collector — Fluent Bit is a common choice — ships them to a central backend: Loki, Elasticsearch/OpenSearch, a cloud logging service, or a SaaS platform.',
      'Every log line should carry service, namespace, Pod, version, and trace ID, but never secrets or personal data.',
      'I configure buffers, backpressure handling, multiline parsing, retention, and access controls, and I alert when the collector itself fails or drops records. During an incident, I start from the affected transaction and its trace ID instead of searching every log in the cluster.',
      '**Kubernetes log triage**',
      "Start with the failing container's current and previous logs, its Pod description, and its ordered events.",
      'On a node, `/var/log/containers/` and `/var/log/pods/` usually hold the container and pod log files. Evidence from kubelet, the runtime, CNI, and the kernel is usually found through the system journal instead — exact paths vary by Linux distribution and runtime.',
      'Compare timestamps against deployments, node pressure, image pulls, probe failures, and network events.',
      "For AKS, use Azure Monitor/Container Insights, Log Analytics, and the enabled AKS diagnostic categories to get evidence from the managed control plane. Don't assume you have direct host access, or that API server, scheduler, and etcd logs sit at fixed paths — a managed control plane doesn't work that way.",
      'Application teams should emit structured logs to stdout/stderr with service, environment, version, and trace ID. Collectors are responsible for redacting secrets and applying buffering, retention, and access controls.',
    ],
    tags: ['kubernetes', 'logging', 'fluent bit'],
  },
  {
    id: 'itv-mymon-56',
    level: 'basic',
    kind: 'open',
    prompt: 'What do you monitor on Linux and Windows servers?',
    probing:
      'Whether you cover CPU, memory, disk, network and services and correlate them with the application.',
    answer: [
      'On both platforms I watch CPU and load, plus the top processes. I watch memory and swap usage, and out-of-memory events. I watch disk capacity, inode usage, disk I/O, and how fast disk usage is growing. I watch network errors and connection counts, service and process state, open ports, certificate expiry, time sync, pending updates, and OS and application logs.',
      'I always compare these against request latency, errors, and traffic, because a host can look perfectly healthy while the application running on it is broken.',
      "On Linux I'd typically use node-exporter, journald, and process or service exporters. On Windows I'd use windows_exporter, Performance Monitor counters, and Event Viewer forwarding. Cloud-native or commercial agents can replace or add to any of these.",
      'Alerts should be based on sustained conditions, owned by a specific team, and linked to a runbook.',
      '**What to monitor and how it flows**',
      'Host monitoring covers:',
      '- CPU utilization, load, context switching and I/O wait\n- Memory availability, cache, swap and out-of-memory events\n- Filesystem capacity, inode use, growth and disk I/O latency\n- Network throughput, errors, drops and connections\n- Process and service health\n- Certificate expiry, time synchronization and operating-system logs',
      '`node-exporter` exposes Linux host metrics on `/metrics`, normally on port `9100`. Windows exporter provides Windows performance counters. Prometheus scrapes these endpoints and Grafana visualizes the stored time series.',
      'Restrict exporter endpoints to the monitoring network because infrastructure metrics reveal operational details. Do not expose port `9100` publicly.',
    ],
    code: [
      {
        title: 'Host monitoring flow',
        language: 'text',
        code: `Host → Node Exporter → Prometheus → Grafana
                              └──→ alert rule → Alertmanager`,
      },
    ],
    tags: ['monitoring', 'linux', 'windows', 'node-exporter'],
  },
  {
    id: 'itv-mymon-57',
    level: 'intermediate',
    kind: 'scenario',
    prompt: 'How do you investigate a high-CPU alert safely?',
    probing:
      'Whether you confirm impact, break down CPU time and preserve evidence before restarting.',
    answer: [
      'First I confirm the alert is real: how long has it been happening, and is it actually affecting users? I check recent traffic and recent changes, then break the CPU time down into user, system, steal, and I/O-wait time to find the responsible process or thread.',
      'Where I can, I collect application and runtime evidence before restarting anything, since a restart destroys that evidence.',
      "To stabilize things, I shift traffic away, scale out, or stop a task I've confirmed is non-essential and runaway. Then I fix the actual cause: bad code, a slow query, a config issue, a scheduled job, or just not enough capacity.",
      "Afterward I confirm user-facing latency and errors are back to normal, check CPU under real load, and improve the alert or add a regression test so it's caught earlier next time.",
    ],
    tags: ['monitoring', 'cpu', 'troubleshooting'],
  },
  {
    id: 'itv-mymon-58',
    level: 'intermediate',
    kind: 'open',
    prompt: 'How do you monitor disk exhaustion?',
    probing:
      'Whether you forecast time-to-full and find what is growing, including deleted-but-open files.',
    answer: [
      'I track filesystem usage, inode usage, growth rate, and a forecast of when it will hit full, plus disk queue depth on collectors and containers.',
      "When investigating, I look for what's actually growing: a specific directory, files that are open but already deleted, logs, temp data, package caches, or genuine application data.",
      "I clean up using supported rotation and cleanup tools, and I never delete a file in production if I don't know what it is. To prevent this from recurring, I rely on retention policies, quotas, separate capacity where it makes sense, and alerts that fire early enough to act safely.",
    ],
    tags: ['monitoring', 'disk', 'capacity'],
  },
  {
    id: 'itv-mymon-59',
    level: 'intermediate',
    kind: 'open',
    prompt: 'How do you identify and investigate the ten highest-memory processes?',
    probing:
      'Whether you sort by RSS, understand its limits and watch a process over time before calling it a leak.',
    answer: [
      'For a point-in-time view I run:',
      'That gives one header line plus the ten highest processes. I sort by RSS rather than VSZ because RSS is the actual resident physical memory in use, though shared memory can still make per-process totals a bit imprecise.',
      '`ps aux --sort=-%mem | head -n 11` works as a shorter alternative.',
      "I don't assume the top process is leaking from a single sample. I check `free -h`, `vmstat 1`, swap usage, and OOM logs. Then I watch that specific PID over time with `pidstat -r -p <pid> 1`, along with application and runtime metrics and historical monitoring data.",
      'I compare the growth pattern against traffic, deployments, and scheduled jobs. If the impact is severe, I scale out or restart gracefully, but only after preserving diagnostics first. Then I fix the actual leak, cache or heap configuration, workload sizing, or resource limit, and confirm memory, latency, and error rate are back to normal under regular load.',
    ],
    code: [
      {
        title: 'Top ten processes by resident memory',
        language: 'bash',
        code: `ps -eo pid,ppid,user,%mem,rss,vsz,etime,cmd --sort=-rss | head -n 11`,
      },
    ],
    tags: ['linux', 'memory', 'ps'],
  },
  {
    id: 'itv-mymon-60',
    level: 'intermediate',
    kind: 'open',
    prompt: 'How do you monitor containers with cAdvisor and kube-state-metrics?',
    probing:
      'Whether you know what cAdvisor and kube-state-metrics each report and the privilege concerns with cAdvisor.',
    answer: [
      "cAdvisor reports container CPU, memory, filesystem, and network usage. It often needs sensitive host mounts and elevated privileges, so review what access it's actually granted.",
      'In AKS, prefer the supported kubelet/cAdvisor scraping built into the cluster monitoring solution, rather than deploying your own broadly privileged container without review. Use kube-state-metrics separately for Kubernetes object state — it reports things like desired vs. available replicas, not actual container resource usage.',
    ],
    tags: ['containers', 'cadvisor', 'kube-state-metrics'],
  },
  {
    id: 'itv-mymon-61',
    level: 'advanced',
    kind: 'scenario',
    prompt:
      'A node-exporter target-down alert fires. How do you investigate it, and how do you handle CPU, memory and disk alerts?',
    probing:
      'Whether you check discovery, reachability and the exporter itself, and separate the causes of host resource alerts.',
    answer: [
      'For a target-down alert I work through these steps:',
      'For a target-down alert:',
      '1. Check Prometheus target discovery, labels and the latest scrape error.\n2. Verify DNS/network reachability and the exporter process or pod.\n3. Query the exporter `/metrics` endpoint from the Prometheus network.\n4. Check TLS/authentication, firewall or NetworkPolicy changes.\n5. Review resource exhaustion and exporter logs.\n6. Restore service and confirm multiple successful scrapes and alert resolution.',
      'For **high CPU**, compare user, system, I/O wait, and steal time to find the responsible process or container. For **memory**, tell cache usage apart from real memory pressure, and check swap, OOM events, and growth trend.',
      'For **disk**, separate capacity, inode, and latency problems.',
      'Service monitoring should check the process, the listening port, its dependencies, and a real health-check transaction, not just restart a failed process forever. Alert on conditions that are sustained and actionable, and on forecasted exhaustion, not every brief blip.',
      'After fix, confirm application latency and errors as well as the host metric.',
    ],
    followUps: [
      'What does the `up` metric prove, and what does it not prove?',
      'How would you alert on forecasted disk exhaustion?',
    ],
    tags: ['prometheus', 'node-exporter', 'troubleshooting'],
  },
  {
    id: 'itv-mymon-62',
    level: 'basic',
    kind: 'open',
    prompt: 'Which database signals would you put on a production dashboard?',
    probing:
      'Whether you watch latency, connections, locks, replication and backups, segmented without exploding cardinality.',
    answer: [
      "I'd track availability, transaction and query rate, P95/P99 latency, error ratio, connection count and pool wait time, CPU/memory/cache usage, disk capacity and latency, lock and deadlock count, replication lag, failover status, backup age and result, and — where it's safe — a real read/write transaction.",
      'I segment these by database, operation, and application, but I avoid unlimited query or user labels, since that drives up cardinality and cost.',
      'Database monitoring needs to cover both the database itself and how the application experiences it.',
      '**What to monitor**, at a glance:',
      '- **Availability**: Connection success rate\n- **Performance**: Query latency, throughput, errors\n- **Connections**: Active/max connections, pool wait time\n- **Resources**: CPU, memory, cache usage, storage capacity, I/O\n- **Data integrity**: Locks, deadlocks, slow queries\n- **Replication**: Replication lag, failover state\n- **Backups**: Backup age, backup result, restore-test evidence',
      "Application and database monitoring data need to share the same time source, service and environment labels, and trace context. Without that, you can't line up a slow request in the app with what the database was doing at that moment.",
      '**Alerting**: Alert based on user impact and the risk of running out of capacity, not on every slow query. A single slow query is usually noise; a rising trend toward connection pool exhaustion is not.',
      "**Sensitive data**: Query text and parameters can contain sensitive data. Redact them before capture, and control who can access stored query logs and how long they're retained.",
    ],
    tags: ['databases', 'monitoring', 'dashboards'],
  },
  {
    id: 'itv-mymon-63',
    level: 'intermediate',
    kind: 'scenario',
    prompt: 'How do you investigate database connection failures?',
    probing:
      'Whether you classify the failure (refused, timeout, TLS, auth, pool) and fix the proven layer.',
    answer: [
      'First I figure out what kind of failure it is: refused, timeout, TLS, authentication, or pool exhaustion. Then I compare application and database logs by time and source.',
      "I check the endpoint and DNS, the network path, the listener's availability, the secret version and identity being used, the certificate, max connections or a pool leak, replication or failover state, and any recent changes.",
      "I fix the layer that's actually proven to be the cause, then confirm with a real transaction, latency, pool recovery, and that unauthorized access is still denied.",
      '**Types of connection failures**',
      'A connection timeout, an authentication failure, a TLS error, and pool exhaustion are all different problems with different causes. Treat them as separate incidents rather than lumping them together as "connection issues."',
    ],
    tags: ['databases', 'connections', 'troubleshooting'],
  },
  {
    id: 'itv-mymon-64',
    level: 'advanced',
    kind: 'open',
    prompt: 'How do monitoring and alerts support a safe database migration?',
    probing:
      'Whether you set baselines and abort thresholds and keep one controlled writer during cutover.',
    answer: [
      'Before the migration, I confirm backup and restore actually work, and I record baseline latency, error rate, locks, capacity, and replication lag.',
      'During an expand-and-contract or blue-green migration, I watch migration progress, lock duration, replication lag, application versions, read/write correctness, and SLOs. Abort thresholds and the owner responsible for that call are agreed on beforehand.',
      'After cutover, I verify data and business transactions through a stability window before removing the old schema or environment.',
      '**Migrations and blue-green changes**',
      'During a migration or a blue-green cutover, watch locks, replication lag, error rate, latency, and data correctness. Keep exactly one controlled writer active during the cutover — two writers at once is how you get data corruption.',
      "**Backups aren't done until tested**",
      "A backup job succeeding is not the same as a backup being usable. Treat a backup as incomplete until you've tested the restore and validated the application against the restored data.",
    ],
    followUps: [
      'What would make you abort the migration?',
      'How do you prove a backup is restorable?',
    ],
    tags: ['databases', 'migration', 'blue-green'],
  },
  {
    id: 'itv-mymon-65',
    level: 'intermediate',
    kind: 'open',
    prompt: 'How do you monitor Jenkins or Azure DevOps pipelines?',
    probing:
      'Whether you monitor delivery metrics such as queue time and DORA metrics, not just build pass/fail.',
    answer: [
      'I export whatever platform, plugin, or API metrics are available to Prometheus or the chosen backend. Then I graph queue time, stage duration, result, retries, flaky tests, agent capacity, artifact transfer time, deployment frequency, lead time, change-failure rate, and recovery time.',
      'I keep labels limited. Commit hashes belong in deployment annotations or logs, not in long-lived metric labels.',
      'An alert should include the pipeline, environment, failed stage, owner, and runbook. A normal build failure notifies the team; a production deployment failure, or a blocked critical path, may page someone.',
      'I compare trends against agent image or tool changes, and fix the flaky or constrained stage instead of just adding more retries.',
      'Pipeline monitoring should cover the full delivery path, not just whether a build passed.',
      '**What to track**, at a glance:',
      '- **Pipeline health**: Queue time, stage duration, success/failure/retry rate, flaky tests\n- **Agent capacity**: Agent saturation — how close agents are to running out of capacity\n- **Artifacts**: Artifact size and transfer time\n- **Delivery performance**: Deployment frequency, lead time, change-failure rate, recovery time',
      'Jenkins can expose metrics through a maintained Prometheus integration. Azure DevOps has its own metrics and APIs that can feed whatever observability backend you use.',
      'Grafana, or another dashboard tool, should show these trends broken down by pipeline, branch, agent pool, and environment.',
      '**Alerting**: Alerts should identify the environment, commit, failed stage, owner, and runbook.',
      'Page someone only for urgent production impact or a blocked critical delivery path. Ordinary build failures should just notify the responsible team, not wake up on-call.',
      '**Security note**: Never expose credentials in pipeline logs. Also avoid high-cardinality labels — labels with too many unique values, like raw usernames or request IDs, that make metrics expensive to store and slow to query.',
    ],
    tags: ['ci/cd', 'jenkins', 'azure devops', 'dora'],
  },
  {
    id: 'itv-mymon-66',
    level: 'advanced',
    kind: 'open',
    prompt: 'How do you integrate observability into deployment gates?',
    probing:
      'Whether your deployment gates use real health signals with minimum traffic and audited overrides.',
    answer: [
      "I deploy one immutable artifact — meaning it's never changed after it's built — and annotate dashboards with its digest and commit. I route a controlled amount of traffic to it, then check error rate, latency, saturation (how close the system is to its limit), and a smoke or business transaction.",
      "The gate uses a fixed observation window and a minimum amount of traffic, so an empty or thin sample can't pass silently.",
      'If the thresholds fail, promotion stops. A controlled rollback or traffic shift runs, followed by the same verification. That action is authorized, limited in scope, and logged.',
      'Teams can only override the gate through an audited approval path, because automated health checks can be wrong too.',
      '**Tagging and correlation**',
      'Tag application dashboards with the commit, artifact digest, and deployment time. This lets you trace a production issue back to the exact build that caused it.',
      '**Deployment gates**: A post-deployment gate should check error rate, latency, saturation, and a real smoke or business transaction before allowing promotion to continue.',
      'Automatic rollback must be:',
      '- Limited in scope\n- Authorized\n- Recorded\n- Verified afterward',
      'A rollback that fires automatically should never hide a recurring root cause — someone still needs to investigate why it triggered.',
    ],
    followUps: [
      'Why does a gate need a minimum amount of traffic?',
      'Who should be able to override a failed gate?',
    ],
    tags: ['ci/cd', 'deployment gates', 'canary'],
  },
  {
    id: 'itv-mymon-67',
    level: 'intermediate',
    kind: 'open',
    prompt: 'How do you implement monitoring for Terraform-managed infrastructure?',
    probing:
      'Whether you ship monitoring in the same modules as the service and prove it works after apply.',
    answer: [
      'I build monitoring into the same Terraform modules as the service itself. Diagnostic settings or log groups, metric and log alerts, dashboards, notification routing, retention, and access controls all live next to the resource they watch, not bolted on afterward.',
      'Service owners still decide what a meaningful signal looks like for their own service. I push back on generic CPU-only alerts, because they rarely tell you whether users are actually affected.',
      'Policy can enforce a baseline level of logging across the org, so nothing ships unmonitored by accident.',
      'CI validates the code and previews the plan before anything is applied. The apply itself runs with only the permissions it actually needs. Afterward, I generate a known test event or a smoke transaction to prove the whole pipeline works end to end — that data really arrives and a notification really fires.',
      'I also monitor the monitoring resources themselves. That includes cardinality, the number of unique label combinations being produced, since it drives cost and retention just as much as raw data volume does.',
      'There are two separate things to monitor here: the infrastructure that Terraform creates, and the Terraform pipeline itself. Both need attention.',
      '**Monitor the infrastructure Terraform creates**',
      'Provision monitoring alongside the infrastructure it watches, not as an afterthought added later. Diagnostic settings or log groups, metric and log alerts, dashboards, notification routing (action groups or topics), retention, and access controls should all live in the same Terraform, Bicep, or CloudFormation resources as the service they belong to — or be enforced through policy so nothing slips through unmonitored.',
      'Reusable modules give every service a safe default. Service owners still decide what a meaningful signal looks like for their own service, and where its alerts should route.',
      '**Validate after every apply**',
      'An apply that finishes successfully, and creates an alert resource or a diagnostic setting, is not proof the monitoring actually works. Check three things afterward:',
      '1. Monitoring data is actually arriving.\n2. Alerts route to the right place.\n3. The application transaction being monitored actually works.',
    ],
    tags: ['terraform', 'iac', 'monitoring'],
  },
  {
    id: 'itv-mymon-68',
    level: 'advanced',
    kind: 'open',
    prompt: 'How do you monitor Terraform changes and drift?',
    probing:
      'Whether you monitor the Terraform pipeline itself, detect drift without silent reverts and protect state.',
    answer: [
      'The pull request pipeline records the results of format checks, validation, and policy checks, along with a reviewed and protected plan. Nothing gets applied without going through that review.',
      'In production, I record whether the apply succeeded, how long it took, how long it waited on a state lock, and any provider or API failures. After the apply, I run infrastructure and application checks to confirm the change actually worked.',
      "Scheduled plans, or the platform's own drift-detection feature, catch changes made outside of Terraform. When that happens, I open a ticket or alert for someone to review. I don't let automation silently overwrite an emergency change someone made by hand.",
      "Terraform state and full plans can contain secrets, so I keep them encrypted and access-controlled rather than sending them to ordinary logs. When a run fails, I compare it against the cloud provider's audit logs, and I make sure the state matches the real resources — reconciling the two — before retrying.",
      '**Monitor the Terraform pipeline itself**',
      'The delivery pipeline is its own thing to watch, separate from the infrastructure it manages:',
      '- Plan and apply duration and result\n- State lock wait time\n- Provider and API errors\n- Drift detection results\n- Policy and security check failures\n- Smoke checks run right after apply',
      'Keep a reviewed, access-controlled plan and a full audit trail for every change. Terraform state and full plans can contain secrets, so their content should never be exported into ordinary logs or metrics.',
      'Production applies should be serialized — one at a time — and alerts need to tell the difference between an active, legitimate lock and a stale one left behind by a failed run.',
      '**Quick reference**, at a glance:',
      '- **Format, validation, and policy results**: Where: PR pipeline; Why it matters: Catches problems before merge\n- **Reviewed plan**: Where: PR pipeline, access-controlled; Why it matters: Audit trail, prevents surprise changes\n- **Apply result and duration**: Where: Production pipeline; Why it matters: Confirms delivery worked\n- **State-lock wait**: Where: Production pipeline; Why it matters: Flags contention or stuck runs\n- **Provider/API failures**: Where: Production pipeline; Why it matters: Surfaces upstream issues early\n- **Drift**: Where: Scheduled plans or platform drift detection; Why it matters: Flags out-of-band changes without silently reverting them\n- **Post-apply smoke check**: Where: Production pipeline; Why it matters: Confirms the real service works, not just that resources exist',
    ],
    followUps: [
      'How would you tell a stale state lock from an active one?',
      'Why should drift detection not auto-revert?',
    ],
    tags: ['terraform', 'drift', 'pipelines'],
  },
  {
    id: 'itv-mymon-69',
    level: 'advanced',
    kind: 'open',
    prompt: 'How do you control monitoring and logging cost without losing visibility?',
    probing:
      'Whether you break observability cost down by owner and signal and cut waste without blind spots.',
    answer: [
      'First I break down cost by owner and by signal type: ingestion, active series, storage, queries, and egress. That shows me where the money is actually going.',
      "Then I cut waste. I remove duplicate collectors, fix labels that can produce unlimited values (a cardinality problem), downsample old metrics, and set log retention and log levels per service. I archive anything I'm required to keep, and I sample normal traces while keeping errors and important transactions in full.",
      'Budgets and anomaly alerts catch any regression early.',
      'Before I remove any data, I ask what SLO, investigation, security case, or compliance requirement depends on it. After a change, I test the dashboards, alerts, and a real incident query to confirm the cost per transaction actually dropped without creating a blind spot.',
      '**Why it matters**: Monitoring data — metrics, logs, and traces — has real business value, but it also costs real money to collect, store, and query. Ingestion volume, the number of active series, retention length, and query load all add up quickly.',
      'Good FinOps practice here means tracking cost by owner and by signal type, then cutting waste without losing the visibility needed for SLOs, incident response, security, and compliance.',
      '**What to track**, at a glance:',
      '- Ingestion volume: bytes, events, samples, spans\n- Active series and cardinality (the number of unique label combinations)\n- Retention period and storage tier\n- Query cost and egress cost\n- Dashboard and query load\n- Cost broken down by team, service, and environment',
      '**How to control cost**',
      "- Tag data by owner so cost is attributed to the right team.\n- Set budgets and anomaly alerts so spikes get caught early.\n- Set retention per signal type — metrics, logs, and traces don't all need the same retention.\n- Aggregate or downsample old metrics instead of keeping full resolution forever.\n- Sample traces, but keep errors and important transactions in full.\n- Control log levels and log rate per service.\n- Use archive tiers for data you must keep but rarely query.\n- Remove duplicate collectors and pipelines.",
      "**What not to cut**: Don't blindly cut security or audit evidence, or any signal that shows real user impact. Before removing a data source, check whether an SLO, an active investigation, or a compliance requirement depends on it.",
      '**Verifying a change**',
      'Every cost optimization should be tested, not just assumed to work. Confirm dashboards still render, alerts still fire correctly, and a representative incident query still returns the right data before calling the change done.',
      '**Short interview answer**',
      'Monitoring cost tracks with ingestion volume, active series, retention, and query load. I control it by tagging data by owner, setting budgets and anomaly alerts, applying per-signal retention and sampling, and removing duplicate collection. Before cutting anything, I check whether it supports an SLO, an investigation, or a compliance requirement — and I verify dashboards, alerts, and incident queries still work afterward.',
    ],
    followUps: [
      'Which single change usually saves the most on metrics cost?',
      'How do you prove a cost cut did not create a blind spot?',
    ],
    tags: ['finops', 'observability', 'cost'],
  },
  {
    id: 'itv-mymon-70',
    level: 'advanced',
    kind: 'scenario',
    prompt: 'Observability cost rises 40% overnight. What do you investigate?',
    probing:
      'Whether you slice the spike to its source, consider security causes and cap only the confirmed source.',
    answer: [
      'I start by slicing the cost by account, service, data type, table or index, metric namespace, team, and hour. That usually points to where the spike started.',
      'Then I look at recent deployments and config changes. Common causes are debug logging left on, duplicate log forwarding, new diagnostic categories, a spike in the number of unique label combinations (cardinality), a change in trace sampling, a retention change, extra egress, or just a real increase in traffic.',
      'I also check security: an unexpected workload or a compromised credential can generate a flood of monitoring data too.',
      "Once I've confirmed the actual source, I cap only that source safely, preserve any evidence I'm required to keep, and tell the owner what happened. For a permanent fix, I add label limits, a reviewed collection policy, quotas and budgets, anomaly alerts, and a cost test that runs whenever monitoring configuration changes.",
      '**Common causes of a cost spike**',
      "- **Debug logging left on**: Sudden jump in log volume, often after a deploy\n- **New high-cardinality label**: A label like user ID or request ID gets attached to a metric, multiplying the series count\n- **Duplicate collection**: The same data forwarded by two agents or pipelines\n- **Overly broad diagnostic settings**: A cloud resource logs everything instead of just what's needed\n- **Trace sampling change**: Sampling rate accidentally set too high\n- **Real traffic growth**: A genuine increase in usage, not a misconfiguration",
    ],
    followUps: [
      'How would a compromised credential show up in monitoring cost?',
      'What guardrail would stop this recurring?',
    ],
    tags: ['finops', 'observability', 'cost', 'incident'],
  },
]
